FROM python:3.11-slim

WORKDIR /app

RUN pip install --upgrade pip

COPY requirements-base.txt requirements-worker.txt ./
RUN pip install --no-cache-dir -r requirements-worker.txt

COPY app/ ./app/
COPY classes/ ./classes/
COPY .env* ./

CMD ["python", "-m", "app.workers.worker"]

